import pytest
from unittest.mock import AsyncMock, patch, MagicMock
from uuid import uuid4

from fuze.activities.orders import payment_charged
from fuze.common.db.models import Payment

@pytest.mark.asyncio
async def test_payment_idempotency():
    """
    Verify that calling payment_charged with an existing idempotency key 
    returns the existing payment ID without creating a new one.
    """
    order_id = str(uuid4())
    token = "idempotency_token_123"
    existing_payment_id = uuid4()
    
    # Mock Session and Repositories
    mock_session = AsyncMock()
    
    # We need to simulate the context manager `async with get_db_session() as session`
    # We patch `get_db_session` to return a context manager that yields our mock session.
    
    with patch("fuze.activities.orders.get_db_session") as mock_get_db_session:
        mock_get_db_session.return_value.__aenter__.return_value = mock_session
        
        # Mock Repository calls
        # We need to mock PaymentRepository and OrderRepository instantiated inside the activity
        with patch("fuze.activities.orders.PaymentRepository") as MockPaymentRepo, \
             patch("fuze.activities.orders.OrderRepository") as MockOrderRepo, \
             patch("fuze.activities.orders.EventRepository") as MockEventRepo:
            
            mock_payment_repo = MockPaymentRepo.return_value
            mock_order_repo = MockOrderRepo.return_value
            mock_event_repo = MockEventRepo.return_value
            
            # Setup: Payment ALREADY exists
            existing_payment = Payment(
                payment_id=existing_payment_id,
                status="SUCCESS",
                idempotency_key=token
            )
            mock_payment_repo.get_payment_by_idempotency_key.return_value = existing_payment
            
            # Action: Call Activity
            result = await payment_charged(order_id, 1000, token)
            
            # Assert: Returns existing ID
            assert result == str(existing_payment_id)
            
            # Assert: Did NOT create new payment
            mock_payment_repo.create_payment.assert_not_called()
            
            # Assert: Did check idempotency
            mock_payment_repo.get_payment_by_idempotency_key.assert_called_with(token)


@pytest.mark.asyncio
async def test_payment_charge_success():
    """
    Verify successful payment charge when no record exists.
    """
    order_id = str(uuid4())
    token = "new_token_456"
    new_payment_id = uuid4()
    
    mock_session = AsyncMock()
    
    with patch("fuze.activities.orders.get_db_session") as mock_get_db_session:
        mock_get_db_session.return_value.__aenter__.return_value = mock_session
        
        with patch("fuze.activities.orders.PaymentRepository") as MockPaymentRepo, \
             patch("fuze.activities.orders.OrderRepository") as MockOrderRepo, \
             patch("fuze.activities.orders.EventRepository") as MockEventRepo:
            
            mock_payment_repo = MockPaymentRepo.return_value
            mock_order_repo = MockOrderRepo.return_value
            mock_event_repo = MockEventRepo.return_value
            
            # Setup: Payment does NOT exist
            mock_payment_repo.get_payment_by_idempotency_key.return_value = None
            
            # Mock create_payment to simulate DB assigning ID (simplification)
            # Actually our code passes the object to create_payment and returns it
            # The UUID is auto-generated by model default usually, but in logic we instantiated it?
            # Let's check logic:
            # new_payment = Payment(..., status="SUCCESS", ...) -> default ID is generated by uuid4()
            # The activity returns str(new_payment.payment_id)
            
            # We mock create_payment to just return what passed so we can inspect it?
            # Actually the code `return payment` from repo does nothing to the object ref if it's already there
            
            # Action: Call Activity
            result = await payment_charged(order_id, 1000, token)
            
            # Assert: create_payment was called
            mock_payment_repo.create_payment.assert_called_once()
            
            # Verify result is a string (UUID)
            assert isinstance(result, str)
            
            # Assert: Order state updated to PAID
            mock_order_repo.update_order_state.assert_called_with(
                UUID(order_id), state="PAID", step="payment_complete"
            )
